### ISSUE TITLE
\

### ISSUE THREAD

**Issue by Saint-Matthieu** [abentele/Fraise#41] opened 2017-01-06 03:19 UTC
\

**Comment by abentele** [comment] 2017-01-08 18:52
Thanks for reporting this issue.
Could you please provide a more detailed description about the steps to reproduce?
What do you mean with "selecting syntax mode"?

**Comment by abentele** [comment] 2017-01-10 06:02
Maybe this issue is already fixed with the current release https://github.com/abentele/Fraise/releases/tag/3.7.7 - please check it.

**Comment by Saint-Matthieu** [comment] 2017-01-10 22:50
I just DL the app, then gone to Preferences and ticked "syntax mode". It was the v3.7.7.

**Comment by Saint-Matthieu** [comment] 2017-01-10 22:52
I'm going to delete my comments bc it gives info of my computer for sec reasons, so please consider this bug and tell me when you read this msg. thx

**Comment by abentele** [comment] 2017-01-11 08:23
I've deleted everything from the report that I don't need. Now there should be no private information remaining. If you don't agree, delete it, I've already copied the report to my computer.

I need some more details: 

Please be more exact: I couldn't find the words "syntax mode" anywhere in the application. Please tell me the exact label and your language. (if you mean "New documents: Syntax colour" in the tab "General" of the English version: I cannot reproduce it) 

Did Fraise also crash when selecting the "syntax mode" (if so, was the current text file empty or not)? Or does it only crash on startup?

Did you open Fraise with a document when it crashed?

**Comment by abentele** [comment] 2017-01-23 10:14
Because there was no response to my questions for about two weeks, and therefore I cannot reproduce it, I close this issue without any solution.
If you reopen it, please answer the questions. Thanks.

**Closed as completed by abentele** 2017-01-23 10:14 UTC
Labels: bug, priority:normal

**Comment by abentele** [comment] 2017-02-13 07:42
I've fixed a crash which maybe is the same as meant by this issue; please try it: https://github.com/abentele/Erbele/releases/tag/3.8
